"""
Django settings for radio_database project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from radio_database import __version__

# Load environment variables from .env file
load_dotenv(override=True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_VERSION = __version__


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-replace-this-in-production-with-environment-variable',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'radios',  # Our main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'radio_database.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'radios.context_processors.app_version',
            ],
        },
    },
]

WSGI_APPLICATION = 'radio_database.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'radio_database'),
        'USER': os.environ.get('DB_USER', 'ashaw'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Accounts & authentication
# Passwords are hashed with Django's default PBKDF2-SHA256 (industry standard;
# never symmetric-encrypt passwords — hashes must be one-way).
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'dashboard'

# Rate limits for the account endpoints (attempts / window).
AUTH_RATE_LIMIT = '10/1h'
SIGNUP_RATE_LIMIT = '5/1h'

# Social logins (Google, Apple, ...) go here once wired in, e.g.:
# AUTHENTICATION_BACKENDS = [
#     'social_core.backends.google.GoogleOAuth2',
#     'django.contrib.auth.backends.ModelBackend',
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media/manual uploads
MANUALS_DIR = os.environ.get('MANUALS_DIR', 'artifacts/manuals').strip('/ ')
FCC_TEST_REPORTS_DIR = os.environ.get('FCC_TEST_REPORTS_DIR', 'artifacts/test_reports').strip('/ ')
RADIO_IMAGES_DIR = os.environ.get('RADIO_IMAGES_DIR', 'artifacts/images').strip('/ ')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR

# Allow same-origin PDFs (manuals, test reports, OET docs) to be framed in the
# split-window viewer on the radio edit page. Cross-origin framing stays blocked.
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Artifact storage location. The ``artifacts/`` folder is bind-mounted into
# the container; the Docker host is expected to mount the SMB share at that
# folder (the ARTIFACTS_STORE_* variables in .env describe the share). Locally
# it is simply the ``artifacts/`` folder on disk.
ARTIFACTS_STORE_TYPE = os.environ.get('ARTIFACTS_STORE_TYPE', 'local')
ARTIFACTS_STORE_HOST = os.environ.get('ARTIFACTS_STORE_HOST', '')
ARTIFACTS_STORE_FOLDER = os.environ.get('ARTIFACTS_STORE_FOLDER', 'artifacts')
ARTIFACTS_USER = os.environ.get('ARTIFACTS_USER', '')
ARTIFACTS_PASSWORD = os.environ.get('ARTIFACTS_PASSWORD', '')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Tailwind settings
TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

# NPM binary path (for django-tailwind)
NPM_BIN_PATH = os.environ.get('NPM_BIN_PATH', '/usr/local/bin/npm')

# Application logging
LOGGING_ENABLED = os.environ.get('LOGGING', 'true').strip().lower() in {'1', 'true', 'yes', 'on'}
LOGS_DIR = os.environ.get('LOGS_DIR', 'logs').strip('/ ')
LOG_DIR = BASE_DIR / LOGS_DIR
if LOGGING_ENABLED:
    os.makedirs(LOG_DIR, exist_ok=True)
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'standard': {
                'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
            },
        },
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
                'formatter': 'standard',
            },
            'app_file': {
                'class': 'logging.handlers.TimedRotatingFileHandler',
                'filename': str(LOG_DIR / 'radio_tracker.log'),
                'formatter': 'standard',
                'when': 'midnight',
                'interval': 1,
                'backupCount': 30,
                'encoding': 'utf-8',
            },
        },
        'loggers': {
            'radios': {
                'handlers': ['console', 'app_file'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': True,
        'handlers': {
            'null': {
                'class': 'logging.NullHandler',
            },
        },
        'root': {
            'handlers': ['null'],
            'level': 'CRITICAL',
        },
        'loggers': {
            'radios': {
                'handlers': ['null'],
                'level': 'CRITICAL',
                'propagate': False,
            },
        },
    }
