# Generated by Django 5.0.14 on 2025-12-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, help_text='Radio manufacturer/brand', max_length=100)),
                ('model', models.CharField(help_text='Radio model name/number', max_length=200)),
                ('fcc_id', models.CharField(blank=True, help_text='FCC ID (e.g., 2AJGM-UV5R)', max_length=50)),
                ('grantee_code', models.CharField(blank=True, help_text='FCC Grantee Code (e.g., 2AJGM)', max_length=20)),
                ('frequency_range', models.CharField(blank=True, help_text='Frequency range (e.g., 144-148 MHz, 430-450 MHz)', max_length=200)),
                ('power_output', models.CharField(blank=True, help_text='Power output (e.g., 5W, 1-5W)', max_length=100)),
                ('modulation', models.CharField(blank=True, help_text='Modulation type (e.g., FM, AM, SSB, DMR)', max_length=100)),
                ('bands', models.CharField(blank=True, help_text='Band support (e.g., VHF/UHF, Dual-band, Tri-band)', max_length=100)),
                ('digital_modes', models.CharField(blank=True, help_text='Digital modes supported (e.g., DMR, D-STAR, C4FM)', max_length=200)),
                ('channels', models.IntegerField(blank=True, help_text='Number of memory channels', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or specifications')),
                ('review_url', models.URLField(blank=True, help_text='eHam.net review URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Radio',
                'verbose_name_plural': 'Radios',
                'ordering': ['brand', 'model'],
                'indexes': [models.Index(fields=['brand', 'model'], name='radios_radi_brand_41e7ed_idx'), models.Index(fields=['fcc_id'], name='radios_radi_fcc_id_0dbd38_idx')],
                'unique_together': {('brand', 'model')},
            },
        ),
    ]
