# Generated by Django 5.1.15 on 2025-12-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='digital_modes',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='frequency_range',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='grantee_code',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='modulation',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='power_output',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='review_url',
        ),
        migrations.AddField(
            model_name='radio',
            name='air_band',
            field=models.CharField(blank=True, help_text='Air band receive capability (Yes/No)', max_length=50),
        ),
        migrations.AddField(
            model_name='radio',
            name='aprs',
            field=models.CharField(blank=True, help_text='APRS support (e.g., Yes, Analog, Digital, Beacon)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='battery_mah',
            field=models.IntegerField(blank=True, help_text='Battery capacity in mAh', null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='cost_approx',
            field=models.CharField(blank=True, help_text='Approximate cost (e.g., $50, $100-150)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='display',
            field=models.CharField(blank=True, help_text='Display type (e.g., LCD, Color TFT, Dot-matrix)', max_length=200),
        ),
        migrations.AddField(
            model_name='radio',
            name='dmr',
            field=models.CharField(blank=True, help_text='DMR support (Yes/No)', max_length=50),
        ),
        migrations.AddField(
            model_name='radio',
            name='freq_bands_tx',
            field=models.CharField(blank=True, help_text='Frequency bands (TX) (e.g., VHF, UHF, 220)', max_length=200),
        ),
        migrations.AddField(
            model_name='radio',
            name='gps',
            field=models.CharField(blank=True, help_text='GPS capability (Yes/No/Optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='radio',
            name='harmonic_suppression',
            field=models.CharField(blank=True, help_text='Harmonic suppression status (e.g., Good, Excellent, Poor)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='intro_year',
            field=models.IntegerField(blank=True, help_text='Year introduced', null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='power_watts',
            field=models.CharField(blank=True, help_text='Power output (e.g., 5W, 10W)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='rebadges_clones',
            field=models.TextField(blank=True, help_text='Known rebadges or clones'),
        ),
        migrations.AddField(
            model_name='radio',
            name='satellite_tracking',
            field=models.CharField(blank=True, help_text='Satellite tracking capability (Yes/No/Native)', max_length=50),
        ),
        migrations.AddField(
            model_name='radio',
            name='website',
            field=models.URLField(blank=True, help_text='Manufacturer website', max_length=500),
        ),
    ]
