# Generated by Django 5.1.15 on 2025-12-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0002_remove_radio_bands_remove_radio_channels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official manufacturer/brand name', max_length=200, unique=True)),
                ('grantee_code', models.CharField(help_text='FCC Grantee Code (e.g., 2AJGM, 2AZSA)', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, help_text='Full legal company name', max_length=500)),
                ('website', models.URLField(blank=True, help_text='Official website', max_length=500)),
                ('country', models.CharField(blank=True, help_text='Country of origin', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the manufacturer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['grantee_code'], name='radios_bran_grantee_a7fef1_idx')],
            },
        ),
    ]
