# Generated by Django 5.1.15 on 2025-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0003_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='bands',
            field=models.CharField(blank=True, help_text='Supported bands (e.g., VHF, UHF, 220)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='channels',
            field=models.CharField(blank=True, help_text='Number of channels (e.g., 128, 200)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_modes',
            field=models.CharField(blank=True, help_text='Digital modes supported (e.g., DMR, C4FM, D-STAR)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='frequency_range',
            field=models.CharField(blank=True, help_text='Frequency range (e.g., 136-174 MHz, 400-480 MHz)', max_length=200),
        ),
        migrations.AddField(
            model_name='radio',
            name='modulation',
            field=models.CharField(blank=True, help_text='Modulation type (e.g., FM, AM, SSB, DMR)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='power_output',
            field=models.CharField(blank=True, help_text='Power output (e.g., 5W, 10W)', max_length=100),
        ),
    ]
