# Generated by Django 5.1.15 on 2025-12-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0004_radio_bands_radio_channels_radio_digital_modes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='channels',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='digital_modes',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='frequency_range',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='modulation',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='power_output',
        ),
    ]
