# Generated by Django 5.1.15 on 2025-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0005_remove_radio_bands_remove_radio_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='grantee_code',
            field=models.CharField(blank=True, help_text='FCC Grantee Code (e.g., 2AJGM, 2AZSA)', max_length=20, null=True, unique=True),
        ),
    ]
