# Generated by Django 5.1.15 on 2025-12-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0006_alter_brand_grantee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='alias',
            field=models.CharField(blank=True, help_text='Short/common brand alias (e.g., Senhaix, Baofeng)', max_length=100),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['alias'], name='radios_bran_alias_7e5c26_idx'),
        ),
    ]
