# Generated by Django 5.1.15 on 2025-12-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0007_add_brand_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='radio_type',
            field=models.CharField(blank=True, choices=[('base', 'Base'), ('mobile', 'Mobile'), ('portable', 'Portable')], help_text='Type of radio (Base, Mobile, Portable)', max_length=20),
        ),
    ]
