# Generated by Django 5.1.15 on 2026-01-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0008_add_radio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='review_url',
            field=models.URLField(blank=True, help_text='Link to review (e.g., eHam.net)', max_length=500),
        ),
    ]
