# Generated by Django 5.1.15 on 2026-05-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0009_radio_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='white_label_vendors',
            field=models.CharField(blank=True, help_text='Comma-separated list of white label vendors', max_length=500),
        ),
        migrations.AddField(
            model_name='radio',
            name='white_label_vendors',
            field=models.CharField(blank=True, help_text='Comma-separated list of white label vendors', max_length=500),
        ),
    ]
