# Generated by Django 5.1.15 on 2026-05-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0010_brand_white_label_vendors_radio_white_label_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='parent_brand',
            field=models.ForeignKey(blank=True, help_text='Select primary brand if this is a subsidiary or shell company (e.g., EVOTE -> Wouxun)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='radios.brand'),
        ),
    ]
