# Generated by Django 5.1.15 on 2026-05-24 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0011_brand_parent_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='is_a_whitelabel',
            field=models.BooleanField(default=False, help_text='Is this radio a white label model?'),
        ),
        migrations.AddField(
            model_name='radio',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='The actual original manufacturer of this radio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufactured_models', to='radios.brand'),
        ),
    ]
