# Generated by Django 5.1.15 on 2026-05-25 22:58

import django.db.models.deletion
import radios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0012_radio_is_a_whitelabel_radio_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_pdf', models.FileField(upload_to=radios.models.manual_upload_to)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('review', 'Needs Review'), ('linked', 'Linked'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to='radios.radio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='radios_radi_status_ac3ddb_idx'), models.Index(fields=['created_at'], name='radios_radi_created_5990c1_idx')],
            },
        ),
    ]
