# Generated by Django 5.1.15 on 2026-05-26 03:34

import django.db.models.deletion
import radios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0013_radiomanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioFCCTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcc_id', models.CharField(db_index=True, max_length=50)),
                ('report_pdf', models.FileField(upload_to=radios.models.test_report_upload_to)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('report_title', models.CharField(blank=True, max_length=500)),
                ('product_designation', models.CharField(blank=True, max_length=300)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcc_test_reports', to='radios.radio')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['fcc_id'], name='radios_radi_fcc_id_bd625b_idx'), models.Index(fields=['created_at'], name='radios_radi_created_0a558d_idx')],
            },
        ),
    ]
