# Generated by Django 5.1.15 on 2026-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0014_radiofcctestreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='last_fccid_lookup_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last FCC ID lookup attempt for this radio', null=True),
        ),
    ]
