# Generated by Django 5.1.15 on 2026-05-28 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0015_radio_last_fccid_lookup_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='youtube_video_urla',
            field=models.TextField(blank=True, help_text='One YouTube URL per line.'),
        ),
        migrations.CreateModel(
            name='RadioOETDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcc_id', models.CharField(db_index=True, max_length=50)),
                ('view_attachment', models.CharField(blank=True, max_length=500)),
                ('exhibit_type', models.CharField(blank=True, max_length=200)),
                ('date_submitted_to_fcc', models.DateField(blank=True, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100)),
                ('date_available', models.DateField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oet_documents', to='radios.radio')),
            ],
            options={
                'ordering': ['exhibit_type', 'view_attachment', 'id'],
                'indexes': [models.Index(fields=['fcc_id'], name='radios_radi_fcc_id_83f990_idx'), models.Index(fields=['exhibit_type'], name='radios_radi_exhibit_e194d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('radio', 'fcc_id', 'document_url', 'view_attachment'), name='uniq_oet_document_per_radio_fcc')],
            },
        ),
    ]
