# Generated by Django 5.1.15 on 2026-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0016_radio_youtube_video_urla_radiooetdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
