# Generated by Django 5.1.15 on 2026-05-28 14:12

import radios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0017_brand_last_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiooetdocument',
            name='document_file',
            field=models.FileField(blank=True, upload_to=radios.models.oet_document_upload_to),
        ),
    ]
