# Generated by Django 5.1.15 on 2026-05-29 01:34

import django.db.models.deletion
import radios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0018_radiooetdocument_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Component label, e.g. 'Main Radio' or 'APRS Module'", max_length=100)),
                ('version', models.CharField(blank=True, help_text="Firmware version string, e.g. 'v1.23'", max_length=100)),
                ('download_url', models.URLField(blank=True, help_text='Official firmware download page URL', max_length=500)),
                ('firmware_file', models.FileField(blank=True, help_text='Optional: upload a copy of the firmware file for local download', null=True, upload_to=radios.models.firmware_upload_to)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this firmware version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_versions', to='radios.radio')),
            ],
            options={
                'verbose_name': 'Radio Firmware',
                'verbose_name_plural': 'Radio Firmware Versions',
                'ordering': ['radio', 'label'],
            },
        ),
    ]
