# Generated by Django 5.1.15 on 2026-05-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0019_radiofirmware'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Full legal company name, e.g. 'Hiroyasu Electronics (Hong Kong) Co., Ltd'", max_length=500, unique=True)),
                ('alias', models.CharField(blank=True, help_text="Common short name used commercially, e.g. 'Hiroyasu'", max_length=200)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brands', models.ManyToManyField(blank=True, help_text='Brand labels this manufacturer sells under', related_name='manufacturers', to='radios.brand')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['full_name'],
            },
        ),
    ]
