# Generated by Django 5.1.15 on 2026-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0021_populate_manufacturers'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiomanual',
            name='doc_type',
            field=models.CharField(choices=[('test_report', 'Test Report'), ('change_in_id', 'Change in Identification'), ('authorization', 'Authorization'), ('manual', 'Manual'), ('firmware', 'Firmware'), ('cps', 'CPS'), ('other', 'Other')], db_index=True, default='manual', max_length=20, verbose_name='Document Type'),
        ),
        migrations.AddIndex(
            model_name='radiomanual',
            index=models.Index(fields=['doc_type'], name='radios_radi_doc_typ_d47de5_idx'),
        ),
    ]
