# Generated by Django 5.1.15 on 2026-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0024_fccsyncstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fccsyncstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
