# Generated by Django 5.1.15 on 2026-06-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0026_ignoredgrantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='oet_page_url',
            field=models.URLField(blank=True, help_text='FCC EAS OET exhibits page URL (auto-populated by FCC Update)', max_length=1000),
        ),
    ]
