# Generated by Django 5.1.15 on 2026-06-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0027_add_oet_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, help_text='Full street/mailing address, used for geo-mapping manufacturing locations.'),
        ),
    ]
