# Generated by Django 5.1.15 on 2026-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0028_add_manufacturer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='geocode_failed',
            field=models.BooleanField(default=False, help_text='Set when Nominatim could not resolve the address.'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
