# Generated by Django 5.1.15 on 2026-06-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0029_add_manufacturer_geocode_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='geocode_precision',
            field=models.CharField(blank=True, help_text='Resolution level achieved: full, city, state, country, or empty when not yet geocoded.', max_length=20),
        ),
    ]
