# Generated by Django 5.1.15 on 2026-06-03 17:01

import django.db.models.deletion
import radios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0030_add_manufacturer_geocode_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=radios.models.radio_image_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Original URL the image was fetched from, if imported via URL.', max_length=500)),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('display_width', models.PositiveIntegerField(blank=True, null=True)),
                ('display_height', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers appear first in the carousel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='radios.radio')),
            ],
            options={
                'verbose_name': 'Radio Image',
                'verbose_name_plural': 'Radio Images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
