# Generated by Django 5.1.15 on 2026-06-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0031_radioimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='intro_year',
        ),
        migrations.AddField(
            model_name='radio',
            name='grant_date',
            field=models.DateField(blank=True, help_text='Date of FCC grant', null=True),
        ),
    ]
