# Generated by Django 5.1.15 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0032_remove_radio_intro_year_radio_grant_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSkippedGrantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee_code', models.CharField(db_index=True, help_text='FCC grantee code to skip during bulk FCC sync (--all-grantees).', max_length=20, unique=True)),
                ('reason', models.CharField(blank=True, help_text="Short reason this grantee is skipped during sync (e.g. 'Rarely adds new models').", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about why this grantee is out of sync scope.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync-Skipped Grantee ID',
                'verbose_name_plural': 'Sync-Skipped Grantee IDs',
                'ordering': ['grantee_code'],
            },
        ),
    ]
