# Generated by Django 5.1.15 on 2026-07-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0033_sync_skipped_grantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fccsyncstate',
            name='last_grantee_sync_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last successful 'Update All Known Grantees' FCC sync. Used as start-date filter on subsequent runs.", null=True),
        ),
    ]
