# Generated by Django 5.1.15 on 2026-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0034_alter_fccsyncstate_last_grantee_sync_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rule_part', models.CharField(blank=True, help_text="Corresponding 47 CFR part, e.g. 'Part 95E'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Radio Service Type',
                'verbose_name_plural': 'Radio Service Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='radio',
            name='authorization_type_summary',
            field=models.CharField(blank=True, help_text="Auto-computed: e.g. 'Certification' or 'Certification + SDoC'", max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='emission_designators_summary',
            field=models.CharField(blank=True, help_text='Auto-computed: unique emission designators across all certifications', max_length=500),
        ),
        migrations.AddField(
            model_name='radio',
            name='firmware_updates',
            field=models.BooleanField(default=False, help_text='Manufacturer provides firmware updates'),
        ),
        migrations.AddField(
            model_name='radio',
            name='removable_antenna',
            field=models.BooleanField(default=True, help_text='Antenna is user-removable (vs. fixed)'),
        ),
        migrations.AddField(
            model_name='radio',
            name='rule_parts_summary',
            field=models.CharField(blank=True, help_text='Auto-computed: unique rule parts across all certifications', max_length=500),
        ),
        migrations.AddField(
            model_name='radio',
            name='unlockable',
            field=models.BooleanField(default=False, help_text='Can be unlocked/widened via key combo or software'),
        ),
        migrations.AddField(
            model_name='radio',
            name='usb_c_charging',
            field=models.BooleanField(default=False, help_text='Has USB-C charging port'),
        ),
        migrations.AddField(
            model_name='radio',
            name='service_types',
            field=models.ManyToManyField(blank=True, help_text='Service classifications for this radio', related_name='radios', to='radios.radioservicetype'),
        ),
        migrations.CreateModel(
            name='RadioCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcc_id', models.CharField(blank=True, help_text='May differ from radio.fcc_id for Change-in-ID grants', max_length=50)),
                ('grant_date', models.DateField(blank=True, null=True)),
                ('authorization_type', models.CharField(blank=True, choices=[('certification', 'Certification'), ('sdoc', "Supplier's Declaration of Conformity (SDoC)"), ('verification', 'Verification')], default='certification', max_length=20)),
                ('rule_parts', models.CharField(blank=True, help_text="Comma-separated 47 CFR parts, e.g. 'Part 95E, Part 90'", max_length=500)),
                ('freq_range_lower_mhz', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('freq_range_upper_mhz', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('power_output_watts', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('power_type', models.CharField(blank=True, help_text='ERP, EIRP, or Conducted', max_length=20)),
                ('emission_designators', models.CharField(blank=True, help_text="Comma-separated, e.g. '11K0F3E, 7K60FXD'", max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='radios.radio')),
            ],
            options={
                'verbose_name': 'Radio Certification',
                'verbose_name_plural': 'Radio Certifications',
                'ordering': ['-grant_date'],
                'indexes': [models.Index(fields=['radio', 'fcc_id'], name='radios_radi_radio_i_c1f35f_idx')],
            },
        ),
    ]
