# Generated by Django 5.1.15 on 2026-07-22 01:43

from django.db import migrations

SERVICE_TYPES = [
    ('GMRS', 'Part 95E', 'General Mobile Radio Service — UHF repeater-capable'),
    ('FRS', 'Part 95B', 'Family Radio Service — low-power UHF, no license needed'),
    ('CB', 'Part 95D', 'Citizens Band — 27 MHz, 40 channels'),
    ('MURS', 'Part 95J', 'Multi-Use Radio Service — 5 VHF channels'),
    ('Amateur', 'Part 97', 'Amateur (ham) Radio — no Part 97 equipment certification required'),
    ('Commercial', 'Part 90', 'Private Land Mobile Radio — business/public safety'),
    ('Marine', 'Part 80', 'Maritime VHF — 156–162 MHz'),
    ('Aviation', 'Part 87', 'VHF Airband — 108–137 MHz AM'),
    ('PoC', 'Parts 22/24/27', 'Push-to-Talk over Cellular — LTE/3G/5G'),
]


def _seed_service_types(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    for index, (name, rule_part, description) in enumerate(SERVICE_TYPES):
        RadioServiceType.objects.update_or_create(
            name=name,
            defaults={
                'rule_part': rule_part,
                'description': description,
                'sort_order': index,
            },
        )


def _unseed_service_types(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    names = [st[0] for st in SERVICE_TYPES]
    RadioServiceType.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0035_radioservicetype_radio_authorization_type_summary_and_more'),
    ]

    operations = [
        migrations.RunPython(_seed_service_types, _unseed_service_types),
    ]
