# Generated by Django 5.1.15 on 2026-07-23

from django.db import migrations

NEW_SERVICE_TYPES = [
    ('Part 15 Subpart B', 'Part 15B', 'Unintentional radiators — RF devices that are not '
     'intentional transmitters (receivers, computers, peripherals)'),
]


def _seed_part15(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    max_order = (
        RadioServiceType.objects.order_by('-sort_order')
        .values_list('sort_order', flat=True)
        .first()
        or 0
    )
    for index, (name, rule_part, description) in enumerate(NEW_SERVICE_TYPES):
        RadioServiceType.objects.update_or_create(
            name=name,
            defaults={
                'rule_part': rule_part,
                'description': description,
                'sort_order': max_order + index + 1,
            },
        )


def _unseed_part15(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    names = [st[0] for st in NEW_SERVICE_TYPES]
    RadioServiceType.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0036_seed_service_types'),
    ]

    operations = [
        migrations.RunPython(_seed_part15, _unseed_part15),
    ]
