# Generated by Django 5.1.15 on 2026-07-23

from django.db import migrations

NEW_SERVICE_TYPES = [
    ('Part 15 Subpart C', 'Part 15C', 'Intentional radiators — devices that intentionally '
     'generate and emit RF energy (transmitters, transceivers)'),
]


def _seed_part15c(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    max_order = (
        RadioServiceType.objects.order_by('-sort_order')
        .values_list('sort_order', flat=True)
        .first()
        or 0
    )
    for index, (name, rule_part, description) in enumerate(NEW_SERVICE_TYPES):
        RadioServiceType.objects.update_or_create(
            name=name,
            defaults={
                'rule_part': rule_part,
                'description': description,
                'sort_order': max_order + index + 1,
            },
        )


def _unseed_part15c(apps, _schema_editor):
    RadioServiceType = apps.get_model('radios', 'RadioServiceType')
    names = [st[0] for st in NEW_SERVICE_TYPES]
    RadioServiceType.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0037_seed_part15_service_type'),
    ]

    operations = [
        migrations.RunPython(_seed_part15c, _unseed_part15c),
    ]
