# Generated by Django 5.1.15 on 2026-07-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0038_seed_part15c_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='bluetooth',
            field=models.BooleanField(default=False, help_text='Has Bluetooth (2.4 GHz ISM band: 2402-2480 MHz). Used for programming and/or wireless audio accessories.'),
        ),
        migrations.AddField(
            model_name='radio',
            name='noaa_wx',
            field=models.BooleanField(default=False, help_text='Receives NOAA Weather Radio (162.40-162.55 MHz). Receive-only VHF weather band.'),
        ),
    ]
