# Generated by Django 5.1.15 on 2026-07-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0039_add_noaa_wx_bluetooth'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='allowlist_terms',
            field=models.JSONField(blank=True, default=list, null=True, help_text="Allowlist terms that matched this radio's FCC record during ingestion (searchable for radio type filtering)"),
        ),
    ]
