# Generated by Django 5.1.15 on 2026-08-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0041_alter_allowlist_terms_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='channels',
            field=models.IntegerField(blank=True, help_text='Number of memory channels', null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='display_color',
            field=models.CharField(blank=True, help_text='Display color (e.g., Color, Monochrome, Color TFT)', max_length=100),
        ),
        migrations.AddField(
            model_name='radio',
            name='is_toy',
            field=models.BooleanField(default=False, help_text='Is this a toy radio (not a functional two-way transceiver)?'),
        ),
        migrations.AddField(
            model_name='radio',
            name='part_number',
            field=models.CharField(blank=True, help_text='Manufacturer part number / SKU / product code', max_length=200),
        ),
        migrations.AddField(
            model_name='radio',
            name='spec_confidence',
            field=models.FloatField(blank=True, help_text='Aggregate extraction confidence (0.0-1.0)', null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='spec_extracted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful spec extraction', null=True),
        ),
        migrations.AddField(
            model_name='radio',
            name='spec_source_url',
            field=models.URLField(blank=True, help_text='Source product page URL for scraped specifications', max_length=1000),
        ),
        migrations.AddField(
            model_name='radio',
            name='usb_chargeable',
            field=models.BooleanField(default=False, help_text='Charges via USB (any connector type)'),
        ),
        migrations.AddField(
            model_name='radio',
            name='usb_programmable',
            field=models.BooleanField(default=False, help_text='Programmable via USB cable/software'),
        ),
    ]
