# Generated by Django 5.1.15 on 2026-08-25 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0042_radio_channels_radio_display_color_radio_is_toy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('price_cents', models.PositiveIntegerField(default=100, help_text='Price in cents (100 = $1.00).')),
                ('interval', models.CharField(default='month', help_text='Billing interval: month, year, ...', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['price_cents'],
            },
        ),
        migrations.CreateModel(
            name='RadioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_handle', models.CharField(blank=True, help_text="Snapshot of the author's public handle at creation time.", max_length=150)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='radios.radio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(blank=True, help_text='FCC call sign (private).', max_length=20)),
                ('membership_active', models.BooleanField(default=False, help_text='Whether the user has an active paid membership.')),
                ('membership_started_at', models.DateTimeField(blank=True, null=True)),
                ('membership_expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='radios.membershipplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
