# Generated by Django 5.1.15 on 2026-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0043_membershipplan_radiocomment_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='bluetooth',
            field=models.BooleanField(default=False, help_text='Has Bluetooth (2.4 GHz ISM band: 2402-2480 MHz). Used for programming and/or wireless audio accessories.', verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='firmware_updates',
            field=models.BooleanField(default=False, help_text='Manufacturer provides firmware updates', verbose_name='Firmware Updates'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='noaa_wx',
            field=models.BooleanField(default=False, help_text='Receives NOAA Weather Radio (162.40-162.55 MHz). Receive-only VHF weather band.', verbose_name='NOAA Weather Radio'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='removable_antenna',
            field=models.BooleanField(default=True, help_text='Antenna is user-removable (vs. fixed)', verbose_name='Removable Antenna'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='unlockable',
            field=models.BooleanField(default=False, help_text='Can be unlocked/widened via key combo or software', verbose_name='Unlockable'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='usb_c_charging',
            field=models.BooleanField(default=False, help_text='Has USB-C charging port', verbose_name='USB-C Charging'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='usb_chargeable',
            field=models.BooleanField(default=False, help_text='Charges via USB (any connector type)', verbose_name='USB Chargeable'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='usb_programmable',
            field=models.BooleanField(default=False, help_text='Programmable via USB cable/software', verbose_name='USB Programmable'),
        ),
    ]
