# Generated by Django 5.1.15 on 2026-08-31 01:26

from django.db import migrations, models


def _truthy(value):
    """Map legacy capability strings to a boolean True."""
    return (value or '').strip().lower().startswith('yes')


def forwards(apps, schema_editor):
    """Move legacy char capabilities into the new boolean fields."""
    radio_model = apps.get_model('radios', 'Radio')
    for radio in radio_model.objects.all().iterator():
        dmr_value = (radio.dmr or '').strip().lower()
        if 'c4fm' in dmr_value:
            radio.digital_c4fm = True
        elif dmr_value.startswith('yes'):
            radio.digital_dmr = True
        radio.air_band_rx = _truthy(radio.air_band)
        radio.air_band_tx = False
        radio.satellite_tracking_bool = _truthy(radio.satellite_tracking)
        radio.save(update_fields=[
            'air_band_rx', 'air_band_tx',
            'digital_dmr', 'digital_c4fm', 'satellite_tracking_bool',
        ])


def backwards(apps, schema_editor):
    """Restore the legacy char capabilities from the new boolean fields."""
    radio_model = apps.get_model('radios', 'Radio')
    for radio in radio_model.objects.all().iterator():
        if radio.digital_c4fm:
            radio.dmr = 'C4FM'
        elif radio.digital_dmr:
            radio.dmr = 'Yes'
        else:
            radio.dmr = 'No'
        radio.air_band = 'Yes' if radio.air_band_rx else 'No'
        radio.satellite_tracking = (
            'Yes' if radio.satellite_tracking_bool else 'No'
        )
        radio.save(update_fields=['air_band', 'dmr', 'satellite_tracking'])


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0044_alter_radio_bluetooth_alter_radio_firmware_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='air_band_rx',
            field=models.BooleanField(default=False, help_text='Receives the air band (108-137 MHz)', verbose_name='Air Band Receive'),
        ),
        migrations.AddField(
            model_name='radio',
            name='air_band_tx',
            field=models.BooleanField(default=False, help_text='Transmits on the air band (108-137 MHz)', verbose_name='Air Band Transmit'),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_c4fm',
            field=models.BooleanField(default=False, help_text='C4FM digital mode (Yaesu System Fusion)', verbose_name='C4FM'),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_dmr',
            field=models.BooleanField(default=False, help_text='DMR (Digital Mobile Radio) digital mode', verbose_name='DMR'),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_m17',
            field=models.BooleanField(default=False, help_text='M17 open-source digital mode', verbose_name='M17'),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_nxdn',
            field=models.BooleanField(default=False, help_text='NXDN digital mode', verbose_name='NXDN'),
        ),
        migrations.AddField(
            model_name='radio',
            name='digital_p25',
            field=models.BooleanField(default=False, help_text='P25 (APCO Project 25) digital mode', verbose_name='P25'),
        ),
        migrations.AddField(
            model_name='radio',
            name='satellite_tracking_bool',
            field=models.BooleanField(default=False, verbose_name='Satellite Tracking'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='radio',
            name='air_band',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='display_color',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='dmr',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='usb_chargeable',
        ),
        migrations.RemoveField(
            model_name='radio',
            name='satellite_tracking',
        ),
        migrations.RenameField(
            model_name='radio',
            old_name='satellite_tracking_bool',
            new_name='satellite_tracking',
        ),
    ]
