# Generated by Django 5.1.15 on 2026-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0045_cleanup_radio_capabilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='satellite_tracking',
            field=models.BooleanField(default=False, help_text='Has satellite tracking capability', verbose_name='Satellite Tracking'),
        ),
    ]
