# Generated by Django 5.1.15 on 2026-09-23 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0049_backfill_oem_brands'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='youtube_videos_refreshed_at',
            field=models.DateTimeField(blank=True, help_text="Last time this radio's YouTube URLs were refreshed.", null=True),
        ),
        migrations.CreateModel(
            name='YouTubeRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_refreshes', to='radios.radio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_refreshes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
