# Generated by Django 5.1.15 on 2026-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0050_radio_youtube_videos_refreshed_at_youtuberefreshlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('user_free', 'User (Free)'), ('vendor', 'Vendor'), ('oem', 'OEM')], db_index=True, default='user_free', help_text='Membership/account tier.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='membership_duration',
            field=models.CharField(choices=[('1', '1 month'), ('6', '6 months'), ('12', '12 months'), ('never', 'Never')], default='1', help_text='Membership length from the date the user was added.', max_length=10),
        ),
    ]
